# Generated by Django 5.2.12 on 2026-04-04 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('nombre_places', models.PositiveIntegerField(default=5)),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reduction_active', models.BooleanField(default=False)),
                ('reduction_pourcentage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(upload_to='cars/main/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('type_image', models.CharField(choices=[('exterieur', 'Extérieur'), ('interieur', 'Intérieur'), ('salon', 'Salon'), ('pneus', 'Pneus'), ('moteur', 'Moteur'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_interne', models.CharField(blank=True, max_length=100)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20)),
                ('carburant', models.CharField(choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('kilometrage_actuel', models.PositiveIntegerField(default=0)),
                ('date_prochain_entretien', models.DateField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.carmodel')),
            ],
            options={
                'ordering': ['car_model__marque', 'car_model__modele', 'immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('cin', models.CharField(blank=True, max_length=50)),
                ('numero_permis', models.CharField(blank=True, max_length=100)),
                ('date_expiration_permis', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('date_entretien', models.DateField()),
                ('kilometrage', models.PositiveIntegerField(default=0)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prochain_entretien_date', models.DateField(blank=True, null=True)),
                ('prochain_entretien_km', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('car_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.carunit')),
            ],
            options={
                'ordering': ['-date_entretien', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reservation', models.CharField(choices=[('normale', 'Réservation normale'), ('complete', 'Réservation complète'), ('admin', 'Réservation admin')], default='admin', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('refusee', 'Refusée'), ('paiement_en_attente', 'Paiement en attente'), ('payee', 'Payée')], default='en_attente', max_length=30)),
                ('requested_transmission', models.CharField(blank=True, choices=[('', 'Toutes'), ('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='', max_length=20)),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('cin', models.CharField(blank=True, max_length=50)),
                ('numero_permis', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('kilometrage_depart', models.PositiveIntegerField(default=0)),
                ('kilometrage_retour', models.PositiveIntegerField(blank=True, null=True)),
                ('prix_par_jour_capture', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes_admin', models.TextField(blank=True)),
                ('est_annulable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.carmodel')),
                ('car_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.carunit')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(default='demo', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('operation_type', models.CharField(choices=[('charge_simple', 'Charge simple'), ('revenu_simple', 'Revenu simple'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('credit_recu', 'Crédit reçu'), ('remboursement_credit', 'Remboursement crédit'), ('avance_recue', 'Avance reçue'), ('avance_versee', 'Avance versée'), ('entretien', 'Entretien'), ('carburant', 'Carburant'), ('piece', 'Pièce de rechange'), ('accident', 'Accident'), ('location', 'Paiement location'), ('autre', 'Autre')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('tiers_nom', models.CharField(blank=True, max_length=150)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='core.carmodel')),
                ('car_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='core.carunit')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='core.client')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='core.reservation')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accident', models.DateField()),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(default='En traitement', max_length=100)),
                ('car_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='core.carunit')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='core.reservation')),
            ],
            options={
                'ordering': ['-date_accident', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SparePartRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piece', models.CharField(max_length=150)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('fournisseur', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('car_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='core.carunit')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='core.maintenancerecord')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
