# Generated by Django 5.2.12 on 2026-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_financeentry_categorie_libre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='operation_type',
            field=models.CharField(choices=[('charge_simple', 'Charge simple'), ('revenu_simple', 'Revenu simple'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('credit_recu', 'Crédit reçu'), ('remboursement_credit', 'Remboursement crédit'), ('avance_recue', 'Avance reçue'), ('avance_versee', 'Avance versée'), ('entretien', 'Entretien'), ('carburant', 'Carburant'), ('piece', 'Pièce'), ('accident', 'Accident'), ('autre', 'Autre')], max_length=40),
        ),
    ]
