# Generated by Django 5.2.12 on 2026-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_financeentry_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='operation_type',
            field=models.CharField(choices=[('charge_simple', 'Charge simple'), ('revenu_simple', 'Revenu simple'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('credit_recu', 'Crédit reçu'), ('remboursement_credit', 'Remboursement crédit'), ('avance_recue', 'Avance reçue'), ('avance_versee', 'Avance versée'), ('capital', 'Apport en capital'), ('retrait', 'Retrait'), ('entretien', 'Entretien'), ('carburant', 'Carburant'), ('piece', 'Pièce de rechange'), ('accident', 'Accident'), ('location', 'Paiement location'), ('autre', 'Autre')], max_length=30),
        ),
    ]
